services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        expose:
            - "9000"
        volumes:
            - .:/var/www
        environment:
            APP_ENV: local
            APP_DEBUG: 'true'
            APP_KEY:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: dd_test
            DB_USERNAME: dd_test
            DB_PASSWORD: password
        depends_on:
            - db
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dd_test
            MYSQL_USER: dd_test
            MYSQL_PASSWORD: password
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            - app
        networks:
            - app-network

volumes:
    mysql_data:

networks:
    app-network:
        driver: bridge
